import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { requireMember } from '@/lib/auth';
import { mkdir, writeFile, unlink } from 'fs/promises';
import path from 'path';
export const runtime='nodejs';
async function saveFile(file:File){const ext=path.extname(file.name).toLowerCase()||'.bin';const safe=`${Date.now()}-${Math.random().toString(36).slice(2)}${ext}`;const dir=path.join(process.cwd(),'public','uploads','media');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,safe),Buffer.from(await file.arrayBuffer()));return `/uploads/media/${safe}`;}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;try{const asset=await db.asset.findUnique({where:{id}});if(!asset)return NextResponse.json({error:'Asset not found.'},{status:404});const {membership}=await requireMember(asset.campaignId);if(membership.role!=='GM')throw new Error('FORBIDDEN');const form=await req.formData();const name=String(form.get('name')||asset.name).trim()||asset.name;const file=form.get('file') as File|null;const url=file&&file.size?await saveFile(file):asset.url;const updated=await db.asset.update({where:{id},data:{name,url,type:String(form.get('type')||asset.type||'IMAGE'),folder:String(form.get('folder')||asset.folder||'OTHER')}});return NextResponse.json(updated);}catch(e:any){return NextResponse.json({error:e.message},{status:e.message==='FORBIDDEN'?403:400});}}
export async function DELETE(_req:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;try{const asset=await db.asset.findUnique({where:{id}});if(!asset)return NextResponse.json({error:'Asset not found.'},{status:404});const {membership}=await requireMember(asset.campaignId);if(membership.role!=='GM')throw new Error('FORBIDDEN');const refs=await Promise.all([db.map.count({where:{campaignId:asset.campaignId,imageUrl:asset.url}}),db.character.count({where:{campaignId:asset.campaignId,portraitUrl:asset.url}}),db.location.count({where:{campaignId:asset.campaignId,imageUrl:asset.url}})]);if(refs.some(Boolean))return NextResponse.json({error:'This image is still used by a map, character, or location. Replace that image first.'},{status:409});await db.asset.delete({where:{id}});if(asset.url.startsWith('/uploads/'))await unlink(path.join(process.cwd(),'public',asset.url.replace(/^\//,''))).catch(()=>{});return NextResponse.json({ok:true});}catch(e:any){return NextResponse.json({error:e.message},{status:e.message==='FORBIDDEN'?403:400});}}
