import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { requireMember } from '@/lib/auth';
import { mkdir, writeFile, unlink } from 'fs/promises';
import path from 'path';
export const runtime='nodejs';
async function saveImage(file:File|null){if(!file||!file.size)return null;const ext=path.extname(file.name).toLowerCase()||'.bin';const safe=`${Date.now()}-${Math.random().toString(36).slice(2)}${ext}`;const dir=path.join(process.cwd(),'public','uploads','locations');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,safe),Buffer.from(await file.arrayBuffer()));return `/uploads/locations/${safe}`;}
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;try{const existing=await db.location.findUnique({where:{id}});if(!existing)return NextResponse.json({error:'Location not found.'},{status:404});const {membership}=await requireMember(existing.campaignId);if(membership.role!=='GM')throw new Error('FORBIDDEN');const form=await req.formData();const parentId=String(form.get('parentId')||'')||null;if(parentId===id)return NextResponse.json({error:'A folder cannot contain itself.'},{status:400});const image=await saveImage(form.get('image') as File|null);const data:any={name:String(form.get('name')||'').trim()||existing.name,type:String(form.get('type')||existing.type||'PLACE'),description:String(form.get('description')||'')||null,gmInfo:String(form.get('gmInfo')||'')||null,parentId};if(image)data.imageUrl=image;const updated=await db.location.update({where:{id},data});return NextResponse.json(updated);}catch(e:any){return NextResponse.json({error:e.message},{status:e.message==='FORBIDDEN'?403:400});}}
export async function DELETE(_req:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;try{const existing=await db.location.findUnique({where:{id}});if(!existing)return NextResponse.json({error:'Location not found.'},{status:404});const {membership}=await requireMember(existing.campaignId);if(membership.role!=='GM')throw new Error('FORBIDDEN');await db.location.updateMany({where:{parentId:id},data:{parentId:existing.parentId}});await db.location.update({where:{id},data:{archived:true}});return NextResponse.json({ok:true});}catch(e:any){return NextResponse.json({error:e.message},{status:e.message==='FORBIDDEN'?403:400});}}
