'use client';
import { useState } from 'react';
import MapHierarchySelect from './MapHierarchySelect';
export default function AdminClient({ maps, characters, locations }: { campaignId:string; maps:any[]; characters:any[]; locations:any[] }) {
  const [mapId,setMapId]=useState(maps[0]?.id||''); const [selected,setSelected]=useState(''); const [placing,setPlacing]=useState(false); const [msg,setMsg]=useState(''); const [zoom,setZoom]=useState(1); const [offset,setOffset]=useState({x:0,y:0}); const [drag,setDrag]=useState<any>(null); const map=maps.find(m=>m.id===mapId)||maps[0];
  function reset(){setZoom(1);setOffset({x:0,y:0})}
  async function place(e:React.PointerEvent<HTMLDivElement>){if(!selected||!map)return;const r=e.currentTarget.getBoundingClientRect();const localX=e.clientX-r.left-r.width/2-offset.x,localY=e.clientY-r.top-r.height/2-offset.y;const x=(localX/zoom+r.width/2)/r.width,y=(localY/zoom+r.height/2)/r.height;const res=await fetch(`/api/maps/${map.id}/markers`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({characterId:selected,x,y})});if(res.ok){setMsg('Character marker saved.');window.location.reload()}else{setMsg((await res.json()).error||'Could not save marker.')}}
  async function removeMarker(id:string){if(!confirm('Remove this character marker from the map?'))return;const r=await fetch(`/api/maps/${map.id}/markers?markerId=${id}`,{method:'DELETE'});if(r.ok)window.location.reload()}
  return <main className="content"><div className="panel"><div className="panel-head"><div><p className="kicker">GM WORKSPACE</p><h3>Map editor</h3></div><a className="ghost" href="/">Back to atlas</a></div><div className="editor-wrap"><div className="editor-toolbar"><MapHierarchySelect maps={maps} value={mapId} onChange={id=>{setMapId(id);reset()}} /><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose character…</option>{characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className={placing?'primary':'ghost'} disabled={!selected} onClick={()=>{setPlacing(v=>!v);setMsg(!placing?'Click the map where the selected character should appear.':'Placement cancelled.')}}>{placing?'Click map to place · active':'Place character'}</button><div className="zoom"><button onClick={()=>setZoom(z=>Math.max(.6,z-.2))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(4,z+.2))}>+</button><button onClick={reset}>Reset</button></div></div><p className="hint">Markers are anchored to the map itself, so panning and zooming keep them attached to the correct place.</p>{msg&&<p className="status">{msg}</p>}{map&&<div className="map-stage interactive" style={{aspectRatio:`${map.width}/${map.height}`,cursor:selected?'crosshair':'grab'}} onPointerDown={e=>{if(placing)return;(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);setDrag({x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y})}} onPointerMove={e=>{if(drag)setOffset({x:drag.ox+e.clientX-drag.x,y:drag.oy+e.clientY-drag.y})}} onPointerUp={e=>{if(placing){void place(e);setPlacing(false)}else setDrag(null)}} onPointerCancel={()=>setDrag(null)}><div className="map-world" style={{transform:`translate(${offset.x}px,${offset.y}px) scale(${zoom})`}}><img src={map.imageUrl} alt={map.name} draggable={false}/>{map.markers.map((m:any)=>{const c=characters.find(x=>x.id===m.entityId);return c?<div key={m.id} className="character-marker static" style={{left:`${m.x*100}%`,top:`${m.y*100}%`}}><span className="marker-name">{c.name}</span><img src={c.portraitUrl||'/assets/chars/character-placeholder.svg'} alt=""/><button className="marker-remove" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();void removeMarker(m.id)}} aria-label={`Remove ${c.name} marker`}>×</button></div>:null})}</div></div>}</div></div></main>
}
