'use client';
import { useState } from 'react';
const blank={name:'',title:'',currentLocationName:'',description:'',publicInfo:'',gmInfo:''};
export default function CharacterManager({initial,role,campaignId,players=[]}:{initial:any[];role:string;campaignId:string;players?:any[]}){
 const [chars,setChars]=useState(initial),[editing,setEditing]=useState<any>(null),[open,setOpen]=useState(false),[error,setError]=useState(''); const canEdit=role==='GM';
 function start(c?:any){setEditing(c?{...c}:({...blank}));setOpen(true);setError('')}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=new FormData(e.currentTarget);form.set('campaignId',campaignId);try{const r=editing.id?await fetch(`/api/characters/${editing.id}`,{method:'PATCH',body:form}):await fetch('/api/characters',{method:'POST',body:form});const data=await r.json().catch(()=>({}));if(!r.ok){setError(data.error||'Could not save character.');return}setChars(v=>editing.id?v.map(x=>x.id===data.id?data:x):[...v,data].sort((a,b)=>a.name.localeCompare(b.name)));setOpen(false)}catch{setError('Could not reach the server. Make sure the development server is running.')}}
 async function remove(c:any){if(!confirm(`Delete ${c.name}?`))return;try{const r=await fetch(`/api/characters/${c.id}`,{method:'DELETE'});if(r.ok)setChars(v=>v.filter(x=>x.id!==c.id));else setError((await r.json()).error||'Could not delete character.')}catch{setError('Could not reach the server.')}}
 async function reveal(c:any,userId?:string){const r=await fetch(`/api/characters/${c.id}/reveal`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(userId?{userId}:{all:true})});if(r.ok){setChars(v=>v.map(x=>x.id===c.id?{...x,revealedPlayerIds:userId?[...(x.revealedPlayerIds||[]),userId]:players.map(p=>p.id)}:x));setError('')}else setError((await r.json()).error||'Could not reveal character.')}
 async function hide(c:any,userId?:string){const url=userId?`/api/characters/${c.id}/reveal?userId=${encodeURIComponent(userId)}`:`/api/characters/${c.id}/reveal`;const r=await fetch(url,{method:'DELETE'});if(r.ok)setChars(v=>v.map(x=>x.id===c.id?{...x,revealedPlayerIds:userId?(x.revealedPlayerIds||[]).filter((id:string)=>id!==userId):[]}:x));}
 return <><div className="page-head"><div><p className="kicker">CAMPAIGN PEOPLE</p><h2>Characters</h2><p>NPCs stay hidden from players until you reveal them.</p></div>{canEdit&&<button className="primary" onClick={()=>start()}>+ Add character</button>}</div>{error&&<p className="form-error">{error}</p>}<div className="character-grid">{chars.map(c=><article className="character-card" key={c.id}><a href={`/characters/${c.id}`}><img src={c.portraitUrl||'/assets/chars/character-placeholder.svg'} alt=""/><div><p className="kicker">CHARACTER</p><h3>{c.name}</h3>{c.title&&<p>{c.title}</p>}{c.currentLocationName&&<small>{c.currentLocationName}</small>} {canEdit&&<small className="visibility-badge">{(c.revealedPlayerIds||[]).length?`Revealed to ${(c.revealedPlayerIds||[]).length} player(s)`:'Hidden from players'}</small>}</div></a>{canEdit&&<><div className="card-actions"><button onClick={()=>start(c)}>Edit</button><button className="danger" onClick={()=>remove(c)}>Delete</button></div><div className="reveal-box"><strong>Player access</strong>{players.length?players.map(p=>{const shown=(c.revealedPlayerIds||[]).includes(p.id);return <div key={p.id} className="reveal-row"><span>{p.displayName}</span><button className="ghost" onClick={()=>shown?hide(c,p.id):reveal(c,p.id)}>{shown?'Hide':'Reveal'}</button></div>}):<small>No players yet.</small>}<button className="ghost" onClick={()=>reveal(c)}>Reveal to all</button></div></>}</article>)}{!chars.length&&<div className="empty">No characters yet.</div>}</div>{open&&<div className="modal-backdrop"><form className="modal" onSubmit={save} encType="multipart/form-data"><div className="modal-head"><div><p className="kicker">{editing.id?'EDIT':'NEW'} CHARACTER</p><h3>{editing.id?'Edit character':'Add character'}</h3></div><button type="button" className="ghost" onClick={()=>setOpen(false)}>Close</button></div><label>Name<input name="name" defaultValue={editing.name} required/></label><label>Portrait<input name="portrait" type="file" accept="image/jpeg,image/png,image/webp,image/gif"/></label><div className="form-grid"><label>Title / role<input name="title" defaultValue={editing.title||''}/></label><label>Current location<input name="currentLocationName" defaultValue={editing.currentLocationName||''}/></label></div><label>Public information<textarea name="publicInfo" defaultValue={editing.publicInfo||''} rows={4}/></label><label>Full description<textarea name="description" defaultValue={editing.description||''} rows={5}/></label><label>GM-only information<textarea name="gmInfo" defaultValue={editing.gmInfo||''} rows={6}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary" type="submit">Save character</button></form></div>}</>;
}
