'use client';
import {useMemo,useState} from 'react';
export default function LocationManager({campaignId,initial}:{campaignId:string;initial:any[]}){
 const [locations,setLocations]=useState(initial),[editing,setEditing]=useState<any>(null),[open,setOpen]=useState(false),[error,setError]=useState(''),[collapsed,setCollapsed]=useState<Record<string,boolean>>({});
 const children=useMemo(()=>{const m=new Map<string|null,any[]>();for(const l of locations){const k=l.parentId||null;m.set(k,[...(m.get(k)||[]),l])}for(const [k,v] of m)m.set(k,v.sort((a,b)=>a.name.localeCompare(b.name)));return m},[locations]);
 function start(l?:any,parentId?:string){setEditing(l?{...l}:({name:'',type:'PLACE',description:'',gmInfo:'',parentId:parentId||'',imageUrl:''}));setOpen(true);setError('')}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);f.set('campaignId',campaignId);try{const r=await fetch(editing?.id?`/api/locations/${editing.id}`:'/api/locations',{method:editing?.id?'PATCH':'POST',body:f});const d=await r.json();if(!r.ok){setError(d.error||'Could not save folder.');return}setLocations(v=>editing?.id?v.map(x=>x.id===d.id?d:x):[...v,d]);setOpen(false)}catch{setError('Could not reach the server.')}}
 async function remove(l:any){if(!confirm(`Remove ${l.name}? Its children will move to its parent.`))return;const r=await fetch(`/api/locations/${l.id}`,{method:'DELETE'});if(r.ok)setLocations(v=>v.filter(x=>x.id!==l.id).map(x=>x.parentId===l.id?{...x,parentId:l.parentId}:x));else setError((await r.json()).error||'Could not remove folder.')}
 function Tree({parentId=null,depth=0}:{parentId?:string|null;depth?:number}){return <>{(children.get(parentId)||[]).map(l=>{const has=(children.get(l.id)||[]).length>0;const isCollapsed=!!collapsed[l.id];return <div key={l.id}><article className="tree-row" style={{marginLeft:depth*22}}><div className="tree-main">{has?<button className="tree-toggle" onClick={()=>setCollapsed(v=>({...v,[l.id]:!v[l.id]}))} aria-label={isCollapsed?`Expand ${l.name}`:`Collapse ${l.name}`}>{isCollapsed?'▸':'▾'}</button>:<span className="tree-spacer"/>}{l.imageUrl?<img src={l.imageUrl} alt=""/>:<span className="folder-icon">{l.type==='COUNTRY'?'◆':l.type==='CITY'?'◇':'▱'}</span>}<div><strong>{l.name}</strong><small>{l.type||'PLACE'}{has?` · ${children.get(l.id)!.length} child${children.get(l.id)!.length===1?'':'ren'}`:''}</small></div></div><div className="card-actions"><button onClick={()=>start(l)}>Edit</button><button onClick={()=>start(undefined,l.id)}>+ Child</button><button className="danger" onClick={()=>remove(l)}>Remove</button></div></article>{!isCollapsed&&<Tree parentId={l.id} depth={depth+1}/>}</div>})}</>}
 return <section className="admin-section"><div className="section-head"><div><p className="kicker">WORLD FOLDERS</p><h2>The Aethdom</h2><p>Expand or collapse every parent. Rename, edit, move, add children, or remove any world folder.</p></div><button className="primary" onClick={()=>start()}>+ New folder</button></div><div className="tree-panel"><Tree/></div>{error&&<p className="form-error">{error}</p>}{open&&<div className="modal-backdrop"><form className="modal" onSubmit={save} encType="multipart/form-data"><div className="modal-head"><div><p className="kicker">WORLD FOLDER</p><h3>{editing?.id?'Edit folder':'New folder'}</h3></div><button type="button" className="ghost" onClick={()=>setOpen(false)}>Close</button></div><label>Name<input name="name" defaultValue={editing?.name||''} required/></label><label>Type<select name="type" defaultValue={editing?.type||'PLACE'}><option>WORLD</option><option>COUNTRY</option><option>CITY</option><option>DISTRICT</option><option>PLACE</option></select></label><label>Parent folder<select name="parentId" defaultValue={editing?.parentId||''}><option value="">No parent / root</option>{locations.filter(l=>l.id!==editing?.id).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Picture<input name="image" type="file" accept="image/*"/></label><label>Description<textarea name="description" defaultValue={editing?.description||''} rows={6}/></label><label>GM-only information<textarea name="gmInfo" defaultValue={editing?.gmInfo||''} rows={5}/></label><button className="primary">Save folder</button></form></div>}</section>
}
